jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/book-of-shevon-v2

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            yarn install --ignore-engines

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: run jest tests
          command: |
            yarn test

      # - run:
      #     name: run percy snapshot tests
      #     command: |
      #       yarn run-percy
